// <auto-generated />
using System;
using HamatetsuScheduler.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamatetsuScheduler.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("process");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.ProcessList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartId");

                    b.HasIndex("ProcessId");

                    b.ToTable("process_lists");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.ScheduleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finish_time");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<int>("SchedulePerDayId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_per_day_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("TargetQuantityPerDay")
                        .HasColumnType("int")
                        .HasColumnName("target_quantity_per_day");

                    b.Property<int>("TargetQuantityTotal")
                        .HasColumnType("int")
                        .HasColumnName("target_quantity_total");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.HasIndex("SchedulePerDayId");

                    b.ToTable("schedule_details");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.SchedulePerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("schedule_per_days");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Part", b =>
                {
                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Customer", "Customer")
                        .WithMany("Parts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.ProcessList", b =>
                {
                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Part", "Part")
                        .WithMany("ProcessLists")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Process", "Process")
                        .WithMany("ProcessLists")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Part");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Schedule", b =>
                {
                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Customer", "Customer")
                        .WithMany("Schedules")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Part", "Part")
                        .WithMany("Schedules")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.ScheduleDetail", b =>
                {
                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Process", "Process")
                        .WithMany("ScheduleDetails")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.SchedulePerDay", "SchedulePerDay")
                        .WithMany("Details")
                        .HasForeignKey("SchedulePerDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("SchedulePerDay");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.SchedulePerDay", b =>
                {
                    b.HasOne("HamatetsuScheduler.Api.Domain.Entity.Schedule", "Schedule")
                        .WithMany("Schedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Customer", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Part", b =>
                {
                    b.Navigation("ProcessLists");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Process", b =>
                {
                    b.Navigation("ProcessLists");

                    b.Navigation("ScheduleDetails");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.Schedule", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("HamatetsuScheduler.Api.Domain.Entity.SchedulePerDay", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
